Costs:
  merits: '&a功勋点数'
  biggold: '&6大金币'
  kill: '&c击杀点数'
Lang:
  inventory-full: "背包已满 清先清理"
  CostLore: '&a使用后获得: '
  PlayerCost: '&a您当前拥有 <cost> &a的数量为 &b<value> &a！'
  SplitString: '&8购买此商品需要以下条件'
  SplitMsgString: '&a商品描述'
  EcoString: '&7>> &e游戏币: &b<value>'
  PointString: '&7>> &9点券: &b<value>'
  ItemString: '&7>> &c物品&7[<item>&7]: &b<value> &c个'
  LoreString: '&7>> &c物品类型&7[<lore>&7]: &b<value> &c个'
  IdString: '&7>> &c货币&7[<item>&7]: &b<value> &c个'
  PermString: '&7>> &c达成条件&7[<perm>&7]！'
  CostString: '&7>> <cost>: &b<value>'
  InvCheckString: '&7>> &c背包剩余&7[<value>&7]空格'
  PAPICheckString: '&7>> &c<text>'
  StrCheckString: '&7>> &c<text>'
  NoneString: '&a- &7点击即可'
  NoShift: '&c该界面不允许使用快捷键填充物品！'
  NoShopItem: '&c该物品还没有写上关键的出售代价字段！'
  NoNeed: '&c您没有足够的条件支付这个物品！'
  BuyOK: '&a兑换成功！'
  MaxItem: '&a您的背包已满，多余的物品已被丢弃在地上！'
  NoShop: '&c商店不存在！'
  ShopCreate: '&a商店创建成功 输入 &b/cshop edit 商店ID&a 即可对商店进行编辑！'
  AlreadyCreate: '&c商店创建失败！该商店已经存在了！'
  LineNull: '&c创建失败！商店行数请填写 &b1-6 &c之间的数字！'
  ShopDelete: '&a商店已删除成功！'
  ShopList: '&9当前已创建的商店有:'
  ReloadClose: '&c插件重载迫使您关闭了该商店界面！'
  LeftCost: '&a您当前拥有的所有货币为:'
  NoCost: '-- &c你狗屁都没有！'
  AddCost: '&a货币 <cost> &a给予成功！本次给予玩家 &f<value> &a！'
  DelCost: '&a货币 <cost> &a减少成功！本次减少玩家 &f<value> &a！'
  CostLose: '&c当前指定的货币不存在或已被删除！'
  Limit: '&7>> &c物品剩余数量: &b<value>'
  PlayerLimit: '&7>> &c您还可购买: &b<value> &c次'
  DayLimit: '&7>> &a今日剩余购买次数: &b<value>'
  ShopRefresh: '&a商店刷新完毕！'
  NoStock: '&a该商品已经没有库存了！'
  NoPermission: '&c您没有打开该商店的权限节点 &a<perm>'
  NoClick: '&c请不要过快点击商品！'
  CostCreate: '&a新的货币创建完成！可以输入 &b/cshop cost list &a查看全部货币！'
  CostCreateNull: '&c货币创建失败，指定的货币已经存在！'
  CostDelete: '&a货币删除成功！'
  CostDeleteNull: '&c货币删除失败，指定的货币不存在！'
  CostRename: '&a货币名称修改成功！'
  CostRenameNull: '&c货币名称修改失败，指定的货币不存在！'
  CostClear: '&a所有玩家数据内的指定货币余额已清空！'
  CostTitle: '&e货币id: &f>>&6 '
  CostName: '&c货币名称: &f'
  ShowLore: '&7此处物品仅供展示，无法单独购买！'
